//! The sandbox's `/etc/hosts`, and the one name Minimal puts in it.
//!
//! A session reaches the host that runs its provider at an address that depends
//! on the provider and on the session's network mode (see
//! [`switch::HOST_ALIAS_NAME`] for the table). Publishing the address as a
//! constant makes every integration written against it break the day the address
//! moves, so `minimald` resolves the per-session address at launch and this
//! module renders it into the sandbox's `/etc/hosts` under a stable name.
//!
//! `/etc/hosts` rather than DNS, deliberately. A `host-net` session on a native
//! Linux daemon shares the host's network namespace and resolves through the
//! *host's* resolver, which Minimal neither owns nor writes to — so a
//! gvproxy-served DNS zone (which is what an own-IP session and an in-VM session
//! use) cannot answer for it. `/etc/hosts` is the one lookup path all four
//! contexts share, it is already synthesized per sandbox alongside
//! `/etc/resolv.conf`, and it needs no live switch, no control-socket round trip,
//! and no ordering against gvproxy startup.
//!
//! The file is written into the sandbox rootfs before spawn (hakoniwa binds
//! `/etc` read-only from `<rootfs>/etc`, so an in-sandbox write would hit a
//! read-only fs), exactly like `/etc/hostname` and the own-IP `/etc/resolv.conf`.

use std::io;
use std::net::Ipv4Addr;
use std::path::{Path, PathBuf};

pub use switch::HOST_ALIAS_NAME;

/// Header written at the top of a generated `/etc/hosts`.
const HEADER: &str = "# Generated by Minimal for this session. Rewritten on every launch.\n";

/// Renders the `/etc/hosts` body for a sandbox whose host is reachable at
/// `host_alias`.
///
/// The loopback entries come first and are always present: the file replaces
/// whatever the synthesized rootfs had (usually nothing), so it must not make
/// `localhost` *less* resolvable than it was. `host_alias` is whatever address
/// reaches the host from inside this particular sandbox — `127.0.0.1` for a
/// host-net session on a native daemon, the switch host alias otherwise.
#[must_use]
pub fn render(host_alias: Ipv4Addr) -> String {
    format!(
        "{HEADER}\
         127.0.0.1\tlocalhost\n\
         ::1\tlocalhost ip6-localhost ip6-loopback\n\
         {host_alias}\t{HOST_ALIAS_NAME}\n"
    )
}

/// Writes the rendered `/etc/hosts` into `rootfs`, returning the path written.
///
/// Unlinks any existing file before writing rather than truncating it in place.
/// The rootfs is assembled by *hardlinking* package trees out of the
/// content-addressed cache, so if any package in the closure ships an
/// `/etc/hosts` then `<rootfs>/etc/hosts` is a second link to a cached object,
/// and writing through it would corrupt that object for every other sandbox
/// that links it. Removing first drops this rootfs's link and leaves a fresh,
/// unshared file.
///
/// # Errors
///
/// Propagates failures to create `<rootfs>/etc`, to unlink an existing entry,
/// or to write the file.
pub fn install(rootfs: &Path, host_alias: Ipv4Addr) -> io::Result<PathBuf> {
    // `/etc` exists only if DNS or user/group synthesis ran, and neither is
    // guaranteed, so create it rather than assume it.
    let etc = rootfs.join("etc");
    std::fs::create_dir_all(&etc)?;
    let path = etc.join("hosts");
    match std::fs::remove_file(&path) {
        Ok(()) => {}
        Err(e) if e.kind() == io::ErrorKind::NotFound => {}
        Err(e) => return Err(e),
    }
    std::fs::write(&path, render(host_alias))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The rendered file is a valid `/etc/hosts`: one `address<TAB>name…` per
    /// line, comments aside, with the alias mapped to the address it was given.
    #[test]
    fn renders_loopback_and_the_host_alias() {
        let body = render(Ipv4Addr::new(100, 64, 255, 254));
        assert!(body.starts_with('#'), "generated marker leads the file");
        assert!(body.contains("127.0.0.1\tlocalhost\n"));
        assert!(body.contains("::1\tlocalhost ip6-localhost ip6-loopback\n"));
        assert!(body.contains("100.64.255.254\thost.min.internal\n"));
        assert!(body.ends_with('\n'), "trailing newline: glibc wants one");

        for line in body.lines().filter(|l| !l.starts_with('#')) {
            let (addr, names) = line.split_once('\t').expect("addr<TAB>names");
            assert!(addr.parse::<std::net::IpAddr>().is_ok(), "bad addr: {addr}");
            assert!(!names.trim().is_empty(), "no names on: {line}");
        }
    }

    /// The whole point of the name: the address is a parameter. A host-net
    /// session on a native Linux daemon reaches the host on plain loopback, and
    /// the same name has to answer with that.
    #[test]
    fn the_alias_address_is_a_parameter_not_a_constant() {
        let native = render(Ipv4Addr::LOCALHOST);
        assert!(native.contains("127.0.0.1\thost.min.internal\n"));
        assert!(
            !native.contains("100.64.255.254"),
            "no switch address leaks into a host-net native session"
        );
    }

    /// `install` creates `/etc` when the rootfs has none — synthesis of
    /// `resolv.conf`/`passwd` is what usually creates it and neither is
    /// guaranteed to have run.
    #[test]
    fn install_creates_etc_and_writes_the_file() {
        let tmp = tempfile::tempdir().unwrap();
        let path = install(tmp.path(), Ipv4Addr::new(100, 64, 255, 254)).unwrap();

        assert_eq!(path, tmp.path().join("etc").join("hosts"));
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("100.64.255.254\thost.min.internal\n"));
    }

    /// The rootfs is assembled by hardlinking package trees out of the
    /// content-addressed cache, so a package that ships `/etc/hosts` leaves this
    /// path as a second link to a cached object. `install` must unlink before
    /// writing: truncating in place would rewrite the cached object itself and
    /// corrupt it for every other sandbox that links it.
    #[test]
    fn install_replaces_a_cache_hardlink_instead_of_writing_through_it() {
        let tmp = tempfile::tempdir().unwrap();
        let cached = tmp.path().join("cached-etc-hosts");
        std::fs::write(&cached, "127.0.0.1 from-a-package\n").unwrap();

        let etc = tmp.path().join("rootfs").join("etc");
        std::fs::create_dir_all(&etc).unwrap();
        std::fs::hard_link(&cached, etc.join("hosts")).unwrap();

        install(&tmp.path().join("rootfs"), Ipv4Addr::LOCALHOST).unwrap();

        // The sandbox sees the generated file...
        let in_sandbox = std::fs::read_to_string(etc.join("hosts")).unwrap();
        assert!(in_sandbox.contains("127.0.0.1\thost.min.internal\n"));
        // ...and the cached object it was linked to is untouched.
        assert_eq!(
            std::fs::read_to_string(&cached).unwrap(),
            "127.0.0.1 from-a-package\n"
        );
    }
}
