[package]
name = "checkouts"
version = "0.0.1"
edition.workspace = true
rust-version = "1.85"
license = "MIT OR Apache-2.0"
publish.workspace = true

[dev-dependencies]

[dependencies]
tempfile.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true

rand = "0.9"
