build_started {
  invocation_id: "5dd2abb9-2cc7-4423-8995-685675c4c8ae"
  timestamp_millis: 1760640889823
  working_directory: "/Users/bweeks/Code/minimal/minpkgs"
  command: "--build-events-file build_events.textproto build --packages tar"
}
build_metadata {
  metadata: [{
    key: "user"
    value: "Brandon Weeks"
  }, {
    key: "commit"
    value: "28b235fd030ac62c9be1095cb9e757f75680eeea"
  }, {
    key: "branch"
    value: "spongebob2"
  }, {
    key: "repo_url"
    value: "git@github.com:gominimal/minpkgs.git"
  }]
}
