[workspace]
members = [
    "crates/build-events",
    "crates/build-events-proto",
    "crates/build-sandbox",
    "crates/cache",
    "crates/checkouts",
    "crates/common",
    "crates/decode",
    "crates/graph",
    "crates/op",
    "crates/minimal",
    "crates/res-proto",
]
resolver = "3"

package.edition = "2024"
package.publish = false

[profile.release]
strip = true
lto = true
codegen-units = 1

[workspace.dependencies]
anyhow = "1.0.100"
blake3 = "1"
bytes = "1.11.0" # keep in sync with reqwest
clap = { version = "4.5", features = ["derive"] }
codespan-reporting = { version = "0.13", features = ["serialization"] } # Keep in sync with nickel-lang-core
copy_dir = "0.1.3"
dirs = "6"
either = { version = "1.15", default-features = false }
flate2 = "1.1"
futures = "0.3"
generational-arena = "^0.2"
google-cloud-gax = "1.4.0"
google-cloud-auth = "1.3.0"
google-cloud-storage = "1.5.0"
hakoniwa = { git = "https://github.com/souk4711/hakoniwa", branch = "main" }
hex = "0.4"
indoc = "^2.0"
lzma-rs = "0.3"
nickel-lang-core = { version = "0.16.1", default-features = false, features = ["format"] }
object = { version = "0.38", default-features = false, features = ["archive", "elf", "read_core", "std"] }
oci-spec = "0.8.3"
path-absolutize = "^3.1"
rand = "0.9"
rayon = "1.11"
regex = "1" # keep in sync with nickel-lang-core
reqwest = { version = "0.12", features = ["stream"] } # keep in sync with google-cloud-gax
rustc-hash = "2.1.1"
serde = { version = "1.0", features = ["derive"] } # Keep within the same minor version as nickel-lang-core
prost = "0.14.1"
prost-build = "0.14.1"
resolv-conf = "0.7"
serde_json = { version = "1.0" }
sha2 = "0.10.9"
shlex = "1.3"
size = "0.5"
smallvec = "1.15"
tar = "0.4"
tempfile = "3.23"
thiserror = "2.0"
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1"
tokio-util = "0.7"
toml = "0.9"
tonic = "0.14.2"
tonic-prost = "0.14.2"
tonic-prost-build = "0.14.2"
tracing = "0.1"
tracing-indicatif = "0.3.14"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
url = "2.5" # keep in sync with reqwest
uuid = { version = "1.19", features = ["v4"] }
zstd = "0.13"

globset = "0.4"

# our crates
build-events = { version = "0.0.1", path = "crates/build-events" }
build-events-proto = { version = "0.0.1", path = "crates/build-events-proto" }
build-sandbox = { path = "crates/build-sandbox" }
graph = { version = "0.0.1", path = "crates/graph" }
cache = { version = "0.0.1", path = "crates/cache" }
checkouts = { version = "0.0.1", path = "crates/checkouts" }
common = { version = "0.0.1", path = "crates/common" }
decode = { version = "0.0.1", path = "crates/decode" }
op = { version = "0.0.1", path = "crates/op" }
res-proto = { version = "0.0.1", path = "crates/res-proto" }
