[workspace]
members = [
    "crates/build-sandbox",
    "crates/minimal",
    "crates/graph",
    "crates/cache",
]
resolver = "3"

[profile.release]
debug = true

[workspace.dependencies]
indoc = "^2.0"
generational-arena = "^0.2"
blake3 = "1"
fxhash = "0.2"
nickel-lang-core = "0.14"

path-absolutize = "^3.1"
tempfile = { version = "3.0" }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
clap = { version = "4.4", features = ["derive"] }
dirs = "6"

# Keep within the same minor version as nickel-lang-core
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

# our crates
build-sandbox = { path = "crates/build-sandbox" }
graph = { version = "0.0.1", path = "crates/graph" }
cache = { version = "0.0.1", path = "crates/cache" }

[patch.crates-io]
nickel-lang-core = { git = "https://github.com/gominimal/nickel" }