[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"
pre-build = [
    # protoc version in apt is too old and chokes on optional keyword in proto3 fmt
    "apt-get update && apt-get install --assume-yes wget unzip",
    "wget https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-linux-x86_64.zip -O /tmp/protoc.zip",
    "unzip /tmp/protoc.zip -d /usr/local",
]
