[base]
repo = "git@github.com:gominimal/pkgs.git"
branch = "main"

[envs.dev]
patch.dir."~/.claude" = "rw"
patch.dir."~/.cargo" = "rw"
patch.file."~/.claude.json" = "rw"
env_vars.CC = "gcc"
packages = [
    # Build needs
    "rust", "gcc", "binutils",
    "pkgconf", "openssl", "linux_headers", "zlib",
    # Shell and claude-code needs
    "bash", "claude-code",
    "git", "skopeo", "coreutils",
    # Network, for now
    "base", "ca-certificates",
]

[tasks.env-smoketest]
env = "dev"
inherit_cwd = true
cmd = """
bash -c "echo 'env:' && env && echo \\"pwd: $(pwd)\\""
"""

[tasks.claude]
env = "dev"
cmd = "claude"

[tasks.test]
env = "dev"
cmd = "cargo --config target.x86_64-unknown-linux-gnu.linker=\\\"gcc\\\" test"

[tasks.shell]
env = "dev"
cmd = "bash -l"

[outputs.bash-img]
type = "oci-image"
packages = ["bash", "coreutils", "diffutils", "findutils", "tar"]
