[base]
repo = "git@github.com:gominimal/pkgs.git"
branch = "main"

[envs.dev]
from_profile = "rust"
packages = [
    # Additional build needs
    "pkgconf", "openssl", "linux_headers", "zlib",
    # Shell and claude-code needs
    "base", "bash", "claude-code",
    "git", "skopeo", "coreutils",
    # Network, for now
    "ca-certificates",
]

[envs.demo]
env_vars.CC = "gcc"
packages = [
    # Build needs
    "gcc", "binutils", "python",
    "pkgconf", "openssl", "linux_headers", "zlib",
    # Shell
    "base", "bash",
    "git", "coreutils",
    # Network,
    "ca-certificates",
    # Vim
    "vim", "btop",
]

[tasks.env-smoketest]
env = "dev"
inherit_cwd = true
cmd = """
bash -c "echo 'env:' && env && echo \\"pwd: $(pwd)\\""
"""

[tasks.claude]
env = "dev"
cmd = "claude"

[tasks.test]
env = "dev"
cmd = "cargo test"

[tasks.shell]
env = "dev"
cmd = "bash -l"

[outputs.bash-img]
type = "oci-image"
packages = ["bash", "coreutils", "diffutils", "findutils", "tar"]
env_vars.test = "ello"
cmd = ["/usr/bin/bash", "-l"]

[tasks.vim]
env = "demo"
cmd = "vim"

[tasks.btop]
env = "demo"
cmd = "btop"

[tasks.demo-shell]
env = "demo"
cmd = "bash -l"

[tasks.python]
env = "demo"
cmd = "python3"
