[package]
name = "cache"
version = "0.0.1"
edition.workspace = true
rust-version = "1.85"
license = "MIT OR Apache-2.0"
publish.workspace = true

[dev-dependencies]
indoc.workspace = true

[dependencies]
blake3.workspace = true
hex.workspace = true
sha2.workspace = true
path-absolutize.workspace = true
tempfile.workspace = true

bytes.workspace = true
reqwest.workspace = true
google-cloud-storage.workspace = true
url.workspace = true

tar.workspace = true
zstd.workspace = true

futures.workspace = true
tokio.workspace = true

serde.workspace = true
serde_json.workspace = true

common = { workspace = true }
graph = { workspace = true }
