[package]
name = "minimald"
version = "0.0.1"
edition.workspace = true
publish.workspace = true

[dependencies]
camino.workspace = true
clap.workspace = true
clap_complete.workspace = true
constcat.workspace = true
dirs.workspace = true
russh.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

futures.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

ot.workspace = true
sessions.workspace = true
stdlib.workspace = true

[dev-dependencies]
tempfile.workspace = true
