#!/bin/sh
# git-remote-min <remote-name> <url>

while read -r cmd arg; do
    case "$cmd" in
    capabilities)
        echo connect
        echo            # blank line ends the capabilities list
        ;;
    connect)
        echo            # blank line: connection established
        exec ssh -o ProxyCommand="socat - UNIX-CONNECT:$HOME/.local/state/minimal/providers/local-0/ssh.sock" \
		 -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null' \
		 local "$arg" "$2"
        ;;
    '')
        exit 0
        ;;
    esac
done
