[package]
name = "mctx"
version = "0.0.1"
rust-version = "1.91"
license.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
check.workspace = true
codespan-reporting.workspace = true
google-cloud-auth.workspace = true
google-cloud-storage.workspace = true
toml.workspace = true
toml_edit.workspace = true
tempfile.workspace = true

futures.workspace = true
tracing.workspace = true
tokio.workspace = true
tokio-util.workspace = true

sandbox2.workspace = true

args.workspace = true
lcache.workspace = true
rcache.workspace = true
common.workspace = true
checkouts.workspace = true
graph.workspace = true
mfile.workspace = true
op.workspace = true
ot.workspace = true
paths.workspace = true
orchestrator.workspace = true
stdlib.workspace = true

[dev-dependencies]
indoc.workspace = true
serial_test.workspace = true
