syntax = "proto3";

import "tarball_format.proto";

// A set of files that can be injected into a build.
message InjectedFiles {
    // A tarball to fetch from the given URL. This variant can be used
    // for stuff from the binary cache as well as outputs from earlier builds.
    //
    // URL can of course be a signed URL.
    message FetchUnpack {
        string url = 1;
        string sha256 = 2;
        TarballFormat format = 3;
    }

    // A source, like a Source in the nickel build-decl. TLDR download public artifact.
    message Source {
        string url = 1;
        string sha256 = 2;
        bool extract = 3;
        string strip_prefix = 4;
    }

    // An indication that the requester will upload files that need to be in
    // the build working-directory in a separate RPC, using the given identifier.
    message FilesUpload {
        string upload_id = 1;
        TarballFormat format = 2;
    }

    // A file with literal bytes included inline. Intended for tiny files - use
    // FilesUpload for anything substantial.
    //
    // Any directory components of path will be created if they do not exist.
    message InlineFile {
        string path = 1;
        bytes data = 2;
    }


    // Specifies where and how the injected files are obtained.
    oneof injected_variant {
        FetchUnpack fetch_unpack = 1;
        Source source = 2;
        FilesUpload files_upload = 3;
        InlineFile inline_file = 4;
    }
    reserved 5 to 14;

    // Where in the container the injected files should be unpacked to.
    enum UnpackDest {
        DEST_UNSPECIFIED = 0;
        DEST_ROOTFS = 1;
        DEST_BUILDDIR = 2;
    }

    // Specifies where in the container the injected files should be unpacked to.
    UnpackDest unpack_to = 15;
}
