[package]
name = "op"
version = "0.0.1"
edition.workspace = true
rust-version = "1.87"
license = "MIT OR Apache-2.0"
publish.workspace = true

[dev-dependencies]
indoc.workspace = true
smallvec.workspace = true

[dependencies]
anyhow.workspace = true
either.workspace = true
flate2.workspace = true
futures.workspace = true
generational-arena.workspace = true
google-cloud-storage.workspace = true
globset.workspace = true
walkdir.workspace = true
hakoniwa.workspace = true
oci-spec.workspace = true
rayon.workspace = true
serde_json.workspace = true
sha2.workspace = true
shlex.workspace = true
size.workspace = true
tar.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tonic.workspace = true
tracing.workspace = true
url.workspace = true

cache.workspace = true
common.workspace = true
decode.workspace = true
graph.workspace = true
mfile.workspace = true
sandbox2.workspace = true
res-proto.workspace = true
