[upstream] # Source of software & tooling
repo = "https://github.com/gominimal/pkgs"
branch = "main"
locked_commit = "7b18160b2c9b00bf7066ac4f13c0ede38734246a"

[harness]
use = "rust"

[defaults]
profile = "dev"
state_key = "dev"

[tasks.claude]
exec = "claude"

[tasks.test]
exec = "cargo test"

[tasks.shell]
exec = "bash -l"

[outputs.bash-img]
type = "oci-image"
packages = ["bash", "coreutils", "diffutils", "findutils", "tar"]
env_vars.test = "ello"
cmd = ["/usr/bin/bash", "-l"]

[tasks.vim]
profile = "demo"
state_key = ""
exec = "vim"

[tasks.btop]
profile = "demo"
state_key = ""
exec = "btop"

[tasks.demo-shell]
profile = "demo"
state_key = "demo"
exec = "bash -l"

[tasks.python]
profile = "demo"
state_key = "demo"
exec = "python3"


[tasks.env-smoketest]
inherit_cwd = true
bash = """
echo 'env:' && env && echo "pwd: $(pwd)"
"""

[stdlib]
repo = "https://github.com/gominimal/std"
branch = "main"
locked_commit = "8e711c067261f9cb0dfcaedc06c32d6a2d84e130"
