[package]
name = "build-events-proto"
version = "0.0.1"
edition.workspace = true
rust-version = "1.85"
license = "MIT OR Apache-2.0"
publish.workspace = true

[dependencies]
async-trait = "0.1"
build-events.workspace = true
minimal_spongebob_community_neoeinstein-prost = { version = "0.5.0-20251016192339-b653b5c17f28.2", registry = "buf" }
minimal_spongebob_community_neoeinstein-tonic = { version = "0.5.0-20251016192339-b653b5c17f28.4", registry = "buf" }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-stream = "0.1"
tonic = { version = "0.14.4", features = ["tls-webpki-roots"] }
tracing.workspace = true

[dev-dependencies]
