[package]
name = "res-proto"
version = "0.0.1"
edition.workspace = true
rust-version = "1.85"
license = "MIT OR Apache-2.0"
publish.workspace = true

[dependencies]
tracing.workspace = true

prost.workspace = true

tonic-prost.workspace = true
tonic-prost-build.workspace = true

[build-dependencies]
prost-build.workspace = true
