[package]
name = "build-sandbox"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
globset.workspace = true
hakoniwa.workspace = true
nickel-lang-core.workspace = true
serde.workspace = true
spongebob = { path = "../spongebob" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
