[package]
name = "build-sandbox"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
hakoniwa.workspace = true
globset.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
spongebob = { path = "../spongebob" }

nickel-lang-core.workspace = true
