[package]
name = "min-client"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "min_client"
path = "src/lib.rs"

[[bin]]
name = "min-client"
path = "src/main.rs"

[dependencies]
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
tokio.workspace = true

[build-dependencies]
prost-build.workspace = true
tonic-prost-build.workspace = true
