[package]
name = "common"
version = "0.0.1"
rust-version = "1.91"
license = "MIT OR Apache-2.0"
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
blake3.workspace = true
tracing.workspace = true

copy_dir.workspace = true
globset.workspace = true
jaq-all.workspace = true
walkdir.workspace = true

bzip2.workspace = true
either.workspace = true
hex.workspace = true
rand.workspace = true
sha2.workspace = true
tar.workspace = true
flate2.workspace = true
lzma-rs.workspace = true
tempfile.workspace = true
zstd.workspace = true

args.workspace = true
nickel-lang-core.workspace = true

bytes.workspace = true
reqwest.workspace = true
futures.workspace = true
tokio.workspace = true
url.workspace = true
google-cloud-auth.workspace = true
google-cloud-storage.workspace = true

resolv-conf.workspace = true

ot.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
