[package]
name = "check"
version = "0.0.1"
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
path-absolutize.workspace = true
futures.workspace = true
nickel-lang-core.workspace = true
object.workspace = true
regex.workspace = true
tempfile.workspace = true
tokio.workspace = true

common.workspace = true
decode.workspace = true
graph.workspace = true
lcache.workspace = true
op.workspace = true
ot.workspace = true
