#!/usr/bin/env bash
#
# git-cliff.sh — run the pinned git-cliff without requiring a local install.
#
# Release notes are generated by git-cliff (config: cliff.toml at the repo
# root). To keep the tool from becoming a prerequisite — the release job,
# `just check-version`, and every contributor need it — this wrapper fetches
# the pinned, SHA-512-verified prebuilt into `.scratch/git-cliff/` on first use
# and execs it, exactly like scripts/package-nfpm.sh does for nfpm and
# scripts/fetch-gvproxy.sh does for gvproxy. No `cargo install`, no PATH entry.
#
# Usage:
#   scripts/git-cliff.sh <git-cliff args...>
#
# The pin (version + per-asset SHA-512) lives in vendor/git-cliff/git-cliff.lock.
# GIT_CLIFF_BIN overrides the resolved binary entirely (for a local build or a
# system install); when set, no fetch happens and the pin is not checked.
#
# Requires: bash, curl, and a SHA-512 tool (sha512sum or shasum).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# die <message> — print it with the script prefix on stderr and exit 1.
die() {
    printf 'git-cliff: %s\n' "$1" >&2
    exit 1
}

# sha512_of <file> — the file's SHA-512 hex digest, via sha512sum or shasum.
sha512_of() {
    if command -v sha512sum >/dev/null 2>&1; then sha512sum "$1" | cut -d' ' -f1
    else shasum -a 512 "$1" | cut -d' ' -f1; fi
}

# An explicit binary wins: a contributor's own git-cliff, a distro package.
if [ -n "${GIT_CLIFF_BIN:-}" ]; then
    [ -x "$GIT_CLIFF_BIN" ] || die "GIT_CLIFF_BIN=$GIT_CLIFF_BIN is not executable"
    exec "$GIT_CLIFF_BIN" "$@"
fi

lock="$ROOT/vendor/git-cliff/git-cliff.lock"
[ -f "$lock" ] || die "no git-cliff pin: $lock"
locked_version="$(sed -n 's/^version=//p' "$lock")"
[ -n "$locked_version" ] || die "no version= line in $lock"
GIT_CLIFF_VERSION="${GIT_CLIFF_VERSION:-$locked_version}"
[ "$GIT_CLIFF_VERSION" = "$locked_version" ] \
    || die "GIT_CLIFF_VERSION=$GIT_CLIFF_VERSION does not match the pin in $lock ($locked_version); bump the lock, not the environment"

# Map the host to one of git-cliff's published target triples.
case "$(uname -s)" in
    Linux)  host_os=unknown-linux-gnu ;;
    Darwin) host_os=apple-darwin ;;
    *)      die "unsupported host OS for the git-cliff fetch: $(uname -s)" ;;
esac
case "$(uname -m)" in
    x86_64)        host_arch=x86_64 ;;
    aarch64|arm64) host_arch=aarch64 ;;
    *)             die "unsupported host arch for the git-cliff fetch: $(uname -m)" ;;
esac
asset="git-cliff-${GIT_CLIFF_VERSION#v}-${host_arch}-${host_os}.tar.gz"
want="$(sed -n "s/^${asset}=//p" "$lock")"
[ -n "$want" ] || die "no pinned digest for ${asset} in $lock"

cache="$ROOT/.scratch/git-cliff"
mkdir -p "$cache"
tarball="$cache/$asset"
if [ ! -f "$tarball" ]; then
    url="https://github.com/orhun/git-cliff/releases/download/${GIT_CLIFF_VERSION}/${asset}"
    echo "git-cliff: downloading ${url}" >&2
    curl -fsSL --retry 3 -o "$tarball.partial" "$url" \
        || die "git-cliff download failed: $url"
    got="$(sha512_of "$tarball.partial")"
    [ "$got" = "$want" ] || {
        rm -f "$tarball.partial"
        die "SHA-512 mismatch for ${asset}: got ${got}, want ${want}"
    }
    mv -f "$tarball.partial" "$tarball"
fi
got="$(sha512_of "$tarball")"
[ "$got" = "$want" ] || {
    rm -f "$tarball"
    die "cached $tarball fails verification (got ${got}, want ${want}); delete $cache and re-fetch"
}

bin="$cache/git-cliff-${GIT_CLIFF_VERSION#v}"
if [ ! -x "$bin" ]; then
    # The release tarball also carries LICENSE/README/completions/manpages;
    # extract the binary only.
    extract="$cache/extract"
    rm -rf "$extract"
    mkdir -p "$extract"
    tar -xzf "$tarball" -C "$extract" --strip-components=1 \
        "$(tar -tzf "$tarball" | grep '/git-cliff$')" 2>/dev/null \
        || tar -xzf "$tarball" -C "$extract"
    found="$(find "$extract" -type f -name git-cliff -perm -u+x | head -n 1)"
    [ -n "$found" ] || die "no git-cliff binary inside $tarball"
    mv -f "$found" "$bin"
    chmod +x "$bin"
    rm -rf "$extract"
fi

exec "$bin" "$@"
