TOOLCHAIN_SYSROOT="/opt/toolchain/x86_64-minimal-linux-gnu/sysroot"
DYNAMIC_LINKER="$TOOLCHAIN_SYSROOT/lib64/ld-linux-x86-64.so.2"
export LD_LIBRARY_PATH="$TOOLCHAIN_SYSROOT/lib64:$TOOLCHAIN_SYSROOT/usr/lib64"

export CC="x86_64-minimal-linux-gnu-gcc"
export CXX="x86_64-minimal-linux-gnu-g++"
export AR="x86_64-minimal-linux-gnu-ar"
export RANLIB="x86_64-minimal-linux-gnu-ranlib"
export LD="x86_64-minimal-linux-gnu-ld"
export STRIP="x86_64-minimal-linux-gnu/bin/strip"
export OBJCOPY="x86_64-minimal-linux-gnu-objcopy"
export OBJDUMP="x86_64-minimal-linux-gnu-objdump"
export NM="x86_64-minimal-linux-gnu-nm"

export CFLAGS="-I/usr/include --sysroot=$TOOLCHAIN_SYSROOT"
export CXXFLAGS="-I/usr/include --sysroot=$TOOLCHAIN_SYSROOT"
export LDFLAGS="-L/usr/lib --sysroot=$TOOLCHAIN_SYSROOT -Wl,--dynamic-linker=$DYNAMIC_LINKER -Wl,-rpath=$TOOLCHAIN_SYSROOT/lib64"
export MAKEFLAGS="-j 8"
