[package]
name = "decode"
version = "0.0.1"
edition.workspace = true
rust-version = "1.85"
license = "MIT OR Apache-2.0"
publish.workspace = true

[dev-dependencies]
indoc.workspace = true

[dependencies]
tempfile.workspace = true
nickel-lang-core.workspace = true
codespan-reporting.workspace = true
serde.workspace = true
serde_json.workspace = true
blake3.workspace = true
rustc-hash.workspace = true
generational-arena.workspace = true
smallvec.workspace = true
tracing.workspace = true

common.workspace = true
