[package]
name = "decode"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dev-dependencies]
indoc.workspace = true

[dependencies]
anyhow.workspace = true
either.workspace = true
tempfile.workspace = true
nickel-lang-core.workspace = true
codespan-reporting.workspace = true
blake3.workspace = true
regex.workspace = true
generational-arena.workspace = true
smallvec.workspace = true

toml.workspace = true
serde.workspace = true
shlex.workspace = true

args.workspace = true
common.workspace = true
mfile.workspace = true
stdlib.workspace = true
