[package]
name = "graph"
version = "0.0.1"
edition.workspace = true
rust-version = "1.85"
license = "MIT OR Apache-2.0"
publish.workspace = true

[dev-dependencies]
indoc.workspace = true
tempfile.workspace = true

[dependencies]
nickel-lang-core.workspace = true
codespan-reporting.workspace = true
blake3.workspace = true
generational-arena.workspace = true
smallvec.workspace = true
tracing.workspace = true

common.workspace = true
checkouts.workspace = true
decode.workspace = true
mfile.workspace = true
