syntax = "proto3";
package res;

import "google/protobuf/timestamp.proto";
import "streams.proto";

// The wire format for messages streamed to the server to create an environment.
message CreateEnvMessage {
  oneof msg {
    // The initiation message of the stream. May only be sent as the first message.
    CreateEnvRequest request = 1;
    // A chunk of data for the stream.
    StreamChunk chunk = 2;
  }
}

// A request to RES to create a new environment.
message CreateEnvRequest {
  // A client-provided identifier for the environment.
  string client_id = 1;
  // The number of minutes the environment should live for before it expires and gets deleted.
  uint32 expiry_minutes = 2;
  reserved 3 to 9;

  // The streams which will be sent to create the environment.
  repeated StreamConfig streams = 10;
}

message CreateEnvResponse {
  // The identifier for the server backing the environment.
  string server_id = 1;
  // When the environment expires and gets cleaned up.
  google.protobuf.Timestamp expires_at = 2;
}
