syntax = "proto3";
package res;

import "streams.proto";

// The wire format for messages streamed to the server to do a build.
message OrchestrateBuildMessage {
  oneof msg {
    // The initiation message of the stream. May only be sent as the first message.
    OrchestrateBuildRequest request = 1;
    // A chunk of data for the stream.
    StreamChunk chunk = 2;
  }
}

// A request to RES to do a build.
message OrchestrateBuildRequest {
  // A client-provided identifier for the build.
  string client_id = 1;
  // Describes the graph stream that will follow this message with idx == 0.
  StreamConfig graph_stream = 2;
  // Stream back stderr/stdout for all builds.
  bool verbose = 3;
  // Save the build outputs to the local cache.
  bool commit = 4;
  // Configure the provided GCS bucket name as the remote cache.
  optional string remote_cache_gcs_bucket = 5;
}

message OrchestrateBuildResponse {
  message SetupResponse {}
  message BuildStart {
    // Identifies the build in question.
    uint32 build_id = 1;
    // The name of the build.
    string name = 2;
    // Whether this is a full build or not.
    bool full_build = 3;
    // The spec hash of the package being built.
    string spec_hash = 4;
  }
  message LogLine {
    // Identifies the build in question.
    uint32 build_id = 1;
    // Whether the line is for standard output or standard error.
    bool stderr = 2;
    // The Log line itself.
    string line = 3;
  }
  message BuildStop {
    // Identifies the build in question.
    uint32 build_id = 1;
  }
  message Hydrate {
    // Identifies the index of the operation.
    uint32 build_id = 1;
    // The name of the object being hydrated.
    string name = 2;
    // The spec hash of the artifact being hydrated.
    string spec_hash = 3;
  }
  message OrchestrationError {
    string msg = 1;
  }

  oneof msg {
    // The initial response of the RPC. May only be sent as the first message.
    SetupResponse resp = 1;
    // A build was started.
    BuildStart start = 2;
    // Some output is being streamed back by a build.
    LogLine line = 3;
    // A build was finished.
    BuildStop stop = 4;
    // An object was hydrated from a cache.
    Hydrate hydrate = 5;

    OrchestrationError err = 6;
  }
}
