syntax = "proto3";

// The wire format for messages streamed to the server in an Upload RPC.
message UploadMessage {
    oneof msg {
        // The initiation message of the stream. May only be sent as the first message.
        UploadRequest request = 1;
        // A chunk of data for the stream.
        UploadChunk chunk = 2;
    }
}

// The initiation data for a stream sent in an Upload RPC. Describes the
// build which this upload is for, as well as which injected_files entry it is populating.
message UploadRequest {
    // Identifies the build this UploadRequest is for.
	message ID {
		oneof id {
			// client-provided identifier
			string client_id = 1;
			// RES-generated identifier
			string server_id = 2;
		}
	}
	// Identifies the build this UploadRequest is for.
	ID id = 1;

	// Identifies which injected_files entry this upload is populating.
	string upload_id = 2;
}

// A chunk of data being carried by this upload.
message UploadChunk {
    bytes data = 1;
}
