//! Scaffolding a default `minimal.toml`.
//!
//! Shared by `minimal init` and minimald's session bootstrap. [`generate_mfile`]
//! renders the file contents; [`scaffold_default_mfile`] resolves the latest
//! upstream commit and writes a default shell-stack file into a directory that
//! has none (e.g. an empty session workspace), so a [`crate::Context`] can be
//! built on it.

use std::path::{Path, PathBuf};

use common::SpecOrigin;
use common::repo_spec::Repo;

use crate::{Config, Context, Error};

/// Default upstream package source used when scaffolding a `minimal.toml`.
pub const DEFAULT_PKGS: &str = "https://github.com/gominimal/pkgs";
/// Branch tracked for [`DEFAULT_PKGS`].
pub const DEFAULT_PKGS_BRANCH: &str = "main";
/// Stack used when no project-specific matcher applies.
const FALLBACK_STACK: &str = "shell";

/// Render a `minimal.toml` for the given upstream `origin`.
///
/// `matched_stack` is `Some((name, build_packages, runtime_packages))` when a
/// stack matcher hit during auto-detection; `None` falls back to the `shell`
/// stack with no extra packages.
pub fn generate_mfile(
    matched_stack: Option<(String, Vec<String>, Vec<String>)>,
    origin: &SpecOrigin,
) -> String {
    // Fall back to the "shell" stack if no project-specific matcher hit.
    let (stack_name, build_packages, runtime_packages) = matched_stack
        .map(|h| (h.0, h.1, h.2))
        .unwrap_or_else(|| (FALLBACK_STACK.to_string(), vec![], vec![]));

    let mut content = String::new();
    content.push_str("# Generated by `minimal init`\n\n");

    // [upstream]
    content.push_str("[upstream] # Source of software & tooling\n");
    match &origin {
        SpecOrigin::Repo(Repo::Git { url, rev, tracking }) => {
            content.push_str(&format!("repo = \"{}\"\n", url));
            if let Some(common::repo_spec::GitRef::Branch(b)) = tracking {
                content.push_str(&format!("branch = \"{}\"\n", b));
            }
            content.push_str(&format!("locked_commit = \"{}\"\n", rev,));
        }
        SpecOrigin::LocalDir { given, .. } => {
            content.push_str(&format!("dir = \"{}\"\n", given.to_str().unwrap()))
        }
        SpecOrigin::Inline => unreachable!(),
    }
    content.push('\n');

    content.push_str("[stack]\n");
    content.push_str(&format!("use = \"{}\"\n", stack_name));
    if !build_packages.is_empty() {
        content.push_str(&format!(
            "build_packages = [{}]\n",
            build_packages
                .into_iter()
                .map(|s| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    if !runtime_packages.is_empty() {
        content.push_str(&format!(
            "runtime_packages = [{}]\n",
            runtime_packages
                .into_iter()
                .map(|s| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    content.push('\n');

    content.push_str("[defaults]\n");
    content.push_str("state_key = \"dev\"\n");
    content.push('\n');
    content.push_str("[tasks.shell]\n");
    content.push_str("interactive = true\n");
    content.push_str("packages = [\"base\"]\n");
    content.push_str("exec = \"bash --noprofile -l\"\n");
    content
}

/// Resolve the latest [`DEFAULT_PKGS_BRANCH`] commit and write a default shell
/// `minimal.toml` into `repo_dir`, returning the written path.
///
/// Used to bootstrap a session whose workspace has no `minimal.toml` yet.
pub fn scaffold_default_mfile(
    config: &Config,
    repo_dir: impl AsRef<Path>,
) -> Result<PathBuf, Error> {
    let (mut vcs, _cache, _stdlib) = Context::sub_setup(config)?;
    let (_dir, rev) = vcs.checkout_of(
        DEFAULT_PKGS,
        checkouts::GitRef::Branch(DEFAULT_PKGS_BRANCH.to_string()),
    )?;

    let origin = SpecOrigin::Repo(Repo::Git {
        url: DEFAULT_PKGS.to_string(),
        rev,
        tracking: Some(common::repo_spec::GitRef::Branch(
            DEFAULT_PKGS_BRANCH.to_string(),
        )),
    });

    let content = generate_mfile(None, &origin);
    let path = repo_dir.as_ref().join(mfile::MFILE_NAME);
    std::fs::write(&path, &content)
        .map_err(|e| Error::IO("writing scaffolded minimal.toml", path.clone(), e))?;
    Ok(path)
}
