//! TEMPORARY: scaffolding a default `minimal.toml` for empty session workspaces.
//!
//! This is a stop-gap. A session whose workspace has no `minimal.toml` (the
//! workspace-upload gap) cannot build a [`crate::Context`], so [`minimald`]
//! writes a default shell-stack one here on first attach. Remove this module
//! once sessions receive their project files (including a real `minimal.toml`)
//! and minimald no longer needs to fabricate one.
//!
//! [`generate_mfile`] below is a deliberate COPY of
//! `minimal::cmd_init::generate_mfile` (and its `DEFAULT_PKGS` /
//! `DEFAULT_PKGS_BRANCH` / `FALLBACK_STACK` constants). It is duplicated rather
//! than shared on purpose: this whole module is temporary, so keeping it
//! self-contained means deleting one file removes the workaround cleanly,
//! without unpicking a refactor of `cmd_init`. Keep the two in sync only if it
//! is cheap to; otherwise let this copy lag — it is on its way out.

use std::path::{Path, PathBuf};

use common::SpecOrigin;
use common::repo_spec::Repo;

use crate::{Config, DaemonContext, Error};

/// TEMPORARY (see module docs): default upstream package source.
const DEFAULT_PKGS: &str = "https://github.com/gominimal/pkgs";
/// TEMPORARY (see module docs): branch tracked for [`DEFAULT_PKGS`].
const DEFAULT_PKGS_BRANCH: &str = "main";
/// TEMPORARY (see module docs): stack used when no matcher applies.
const FALLBACK_STACK: &str = "shell";

/// TEMPORARY (see module docs): resolve the latest [`DEFAULT_PKGS_BRANCH`]
/// commit and write a default shell `minimal.toml` into `repo_dir`, returning
/// the written path. Used to bootstrap a session workspace that has none.
pub fn scaffold_default_mfile(
    config: &Config,
    repo_dir: impl AsRef<Path>,
) -> Result<PathBuf, Error> {
    let (mut vcs, _cache, _stdlib) = DaemonContext::sub_setup(config)?;
    let (_dir, rev) = vcs.checkout_of(
        DEFAULT_PKGS,
        checkouts::GitRef::Branch(DEFAULT_PKGS_BRANCH.to_string()),
    )?;

    let origin = SpecOrigin::Repo(Repo::Git {
        url: DEFAULT_PKGS.to_string(),
        rev,
        tracking: Some(common::repo_spec::GitRef::Branch(
            DEFAULT_PKGS_BRANCH.to_string(),
        )),
    });

    let content = generate_mfile(None, &origin);
    let path = repo_dir.as_ref().join(mfile::MFILE_NAME);
    std::fs::write(&path, &content)
        .map_err(|e| Error::IO("writing scaffolded minimal.toml", path.clone(), e))?;
    Ok(path)
}

/// TEMPORARY (see module docs): a verbatim copy of
/// `minimal::cmd_init::generate_mfile`. Renders a `minimal.toml` for the given
/// upstream `origin`; `matched_stack` falls back to the `shell` stack here since
/// minimald does no project auto-detection.
fn generate_mfile(
    matched_stack: Option<(String, Vec<String>, Vec<String>)>,
    origin: &SpecOrigin,
) -> String {
    // Fall back to the "shell" stack if no project-specific matcher hit.
    let (stack_name, build_packages, runtime_packages) = matched_stack
        .map(|h| (h.0, h.1, h.2))
        .unwrap_or_else(|| (FALLBACK_STACK.to_string(), vec![], vec![]));

    let mut content = String::new();
    content.push_str("# Generated by `minimal init`\n\n");

    // [upstream]
    content.push_str("[upstream] # Source of software & tooling\n");
    match &origin {
        SpecOrigin::Repo(Repo::Git { url, rev, tracking }) => {
            content.push_str(&format!("repo = \"{}\"\n", url));
            if let Some(common::repo_spec::GitRef::Branch(b)) = tracking {
                content.push_str(&format!("branch = \"{}\"\n", b));
            }
            content.push_str(&format!("locked_commit = \"{}\"\n", rev,));
        }
        SpecOrigin::LocalDir { given, .. } => {
            content.push_str(&format!("dir = \"{}\"\n", given.to_str().unwrap()))
        }
        SpecOrigin::Inline => unreachable!(),
    }
    content.push('\n');

    content.push_str("[stack]\n");
    content.push_str(&format!("use = \"{}\"\n", stack_name));
    if !build_packages.is_empty() {
        content.push_str(&format!(
            "build_packages = [{}]\n",
            build_packages
                .into_iter()
                .map(|s| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    if !runtime_packages.is_empty() {
        content.push_str(&format!(
            "runtime_packages = [{}]\n",
            runtime_packages
                .into_iter()
                .map(|s| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    content.push('\n');

    content.push_str("[defaults]\n");
    content.push_str("state_key = \"dev\"\n");
    content.push('\n');
    content.push_str("[tasks.shell]\n");
    content.push_str("interactive = true\n");
    content.push_str("packages = [\"base\"]\n");
    content.push_str("exec = \"bash --noprofile -l\"\n");
    content
}
