[package]
name = "build-events"
version = "0.0.1"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
edition.workspace = true
publish.workspace = true

[dependencies]
async-trait = "0.1"
minimal_spongebob_community_neoeinstein-prost = { version = "0.5.0-20251016192339-b653b5c17f28.2", registry = "buf" }
prost = "0.14"
prost-reflect = { version = "0.16", features = ["text-format"] }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tracing-subscriber.workspace = true
