[package]
name = "minimal"
version = "0.1.0"
edition = "2024"

[dependencies]
"build-sandbox" = { workspace = true }
"nickel-proto" = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
petgraph = "0.6"
clap = { version = "4.4", features = ["derive"] }
generational-arena = "0.2"
