[package]
name = "spongebob"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
minimal_spongebob_community_neoeinstein-prost = { version = "0.4.0-20251007185801-98893cf03142.1", registry = "buf" }
minimal_spongebob_community_neoeinstein-tonic = { version = "0.4.1-20251007185801-98893cf03142.1", registry = "buf" }
thiserror.workspace = true
tonic = "0.12.3"
tracing.workspace = true
uuid.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
